language: python
python:
- "3.2"
- "3.3"
- "3.4"
- "3.5"
- nightly
- pypy3
sudo: required
dist: trusty
addons:
  apt:
    packages:
    - libespeak1
cache:
  directories:
  - $HOME/.cache/pip
before_install:
- no_pylint=true
- \[ "$TRAVIS_PYTHON_VERSION" = 3.2 ] ||
  \[ "$TRAVIS_PYTHON_VERSION" = pypy3 ] ||
  no_pylint=false
install:
- \[ "$TRAVIS_PYTHON_VERSION" = "3.2" ] || pip install --upgrade pip
- pip install pyflakes
- $no_pylint || pip install pylint
- pip install docutils
- \[ "$TRAVIS_PYTHON_VERSION" = "3.2" ] || pip install pygments
script:
- python3 -m nose --verbose
- private/run-pyflakes
- $no_pylint || private/run-pylint
- \[ "$TRAVIS_PYTHON_VERSION" = "3.2" ] || find -name '*.rst' | xargs -L1 -t -I{} rst2xml.py --strict {} /dev/null

# vim:ts=2 sts=2 sw=2 et
