language: python
python:
- "3.2"
- "3.3"
- "3.4"
- "3.5"
- nightly
- pypy3
matrix:
  allow_failures:
  - python: pypy3
addons:
  apt:
    packages:
    - espeak
cache:
  directories:
  - $HOME/.cache/pip
install:
- pip install pyflakes
script:
- python3 -m nose --verbose
- ./private/run-pyflakes

# vim:ts=2 sts=2 sw=2 et
