language: python
python:
- "3.2"
- "3.3"
- "3.4"
- "3.5"
- nightly
- pypy3
matrix:
  allow_failures:
  - python: pypy3
sudo: required
dist: trusty
addons:
  apt:
    packages:
    - libespeak1
cache:
  directories:
  - $HOME/.cache/pip
install:
- \[ "$TRAVIS_PYTHON_VERSION" = "3.2" ] || pip install --upgrade pip
- pip install pyflakes
- \[ "$TRAVIS_PYTHON_VERSION" = "3.2" ] || pip install pylint
- pip install docutils
- \[ "$TRAVIS_PYTHON_VERSION" = "3.2" ] || pip install pygments
script:
- python3 -m nose --verbose
- private/run-pyflakes
- \[ "$TRAVIS_PYTHON_VERSION" = "3.2" ] || private/run-pylint
- \[ "$TRAVIS_PYTHON_VERSION" = "3.2" ] || find -name '*.rst' | xargs -L1 -t -I{} rst2xml.py --strict {} /dev/null

# vim:ts=2 sts=2 sw=2 et
