language: python
python:
- "3.2"
- "3.3"
- "3.4"
- "3.5"
- "3.6-dev"
- "3.7-dev"
- pypy3
env:
- NG=
- NG=1
sudo: required
dist: trusty
addons:
  apt:
    packages:
    - autoconf
    - automake
    - libespeak1
    - libtool
cache: pip
before_install:
- no_pylint=true
- \[ "$TRAVIS_PYTHON_VERSION" = 3.2 ] ||
  \[ "$TRAVIS_PYTHON_VERSION" = pypy3 ] ||
  [[ "$TRAVIS_PYTHON_VERSION" =~ dev ]] ||
  no_pylint=false
install:
- \[ "$TRAVIS_PYTHON_VERSION" = "3.2" ] || pip install --upgrade pip
- pip install pyflakes
- $no_pylint || pip install pylint
- pip install docutils
- \[ "$TRAVIS_PYTHON_VERSION" = "3.2" ] || pip install pygments
script:
- \[ ! "$NG" ] || git clone --depth 1 https://github.com/espeak-ng/espeak-ng
- \[ ! "$NG" ] || (cd espeak-ng && ./autogen.sh && ./configure)
- \[ ! "$NG" ] || make -C espeak-ng
- \[ ! "$NG" ] || sudo make -C espeak-ng install
- \[ ! "$NG" ] || sudo ldconfig
- \[ ! "$NG" ] || rm -rf espeak-ng
- \[ ! "$NG" ] || python3 anorack --version | grep -w NG
- python3 -m nose --verbose
- private/run-pyflakes
- $no_pylint || private/run-pylint
- make -C doc

# vim:ts=2 sts=2 sw=2 et
